### ISSUE TITLE
Use Old Gossip API

### ISSUE THREAD

**Issue by noxcis12** [azerothcore/mod-guild-zone-system#11]
uses the old gossip api not work for the lastest version of azerothcore

**Comment by Helias** [comment]
you need to change it as described here
https://github.com/azerothcore/azerothcore-wotlk/pull/1338

**Comment by noxcis12** [comment]
Okay thx :)

**Comment by Helias** [comment]
I am changing it and made a PR for it https://github.com/azerothcore/mod-guild-zone-system/pull/12
