### ISSUE TITLE
Revert SQL changes

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-guild-zone-system#2]
Run this on your world DB if you want to revert the module's SQL:

```
-- The example of the creature --
DELETE FROM `creature_template` WHERE entry=55005;

-- All creatures for guild houses --
DELETE FROM `creature` WHERE id=55005;

DROP TABLE `guildhouses`;
```

**Comment by Helias** [comment]
I think we should add in the README of the repo instead of in a issue.

**Comment by FrancescoBorzi** [comment]
even better: these should be part of the uninstall process of the module

I remember @Yehonal mentioned that it is possible to add uninstalling procedure to modules. Do we have a guide for it?

**Comment by BarbzYHOOL** [comment]
no we have nothing for it and i just put it there to help people because I probably will not use this module at all (i didn't test the module yet, but i bet it will be broken and not very good)

**Comment by BarbzYHOOL** [comment]
Added to readme meanwhile cause i edited it lol
