### ISSUE TITLE
Sql needs to be checked

### ISSUE THREAD

**Issue by arman1717** [azerothcore/mod-guild-zone-system#5]
COLUMN `spawndist` now is  `wander_distance`

**Comment by BarbzYHOOL** [comment]
@arman1717 can you change it?

click here https://github.com/azerothcore/mod-guild-zone-system/blob/master/sql/world/creatures.sql then click on the "pencil" icon, then change it and make your first pull request!

**Comment by arman1717** [comment]
Closed with #6
